# Define the other configuration files (tab separated values)
# These files must have the columns below unless you want to modify many things
#-----------------------------------------------------------------------------#
# SYSTEMS:
# Path	System	Replicate	Parm_Path	Sys_Tag Start_Prod_Range
# End_Prod_Range	Sim_Time
# ---------
# Path: the path within the analysis directory created by the workflow.
#  It should be system/replicate.
# System: the system to analyze.
# Replicate: which replicate to use.
# Parm_Path: the path to the prmtop, inpcrd, and trajectory files
# Sys_Tag: how the associated prmtop, inpcrd, and trajectory information is
#  named. BLAH.prmtop, BLAH.inpcrd, BLAH{F_SEP}md1.mdcrd or BLAH{F_SEP}md1.nc
# Start_Prod_Range and End_Prod_Range: the production frames for the
#  trajectory labels (ex: 25-350 as ns)
# Sim_Time: the expected amount of simulation time to use for the graphs,
# in nano seconds. This should probably be End_Prod_Range - Start_Prod_Range
#-----------------------------------------------------------------------------#
# EDAVALS:
# Path	NRES	NATOM	NPROTAT	TOTRES
#-----------------------------------------------------------------------------#
# EDACOMPS:
# SysA-SysB	SystemA	A_Path	SystemB	B_Path
#-----------------------------------------------------------------------------#

SYSTEMS: "config/systems.tsv"
EDAVALS: "config/EDAvalues.tsv"
EDACOMPS: "config/EDAcompare.tsv"

#---------------------------------- Overall ----------------------------------#

# Project identifier
# Most output files will be {PROJ_TAG}{F_SEP}{SYSTEM}
#  (sometimes {PROJ_TAG}{F_SEP}{SYSTEM}{F_SEP}{REPLICATE})
# If you value consistency, make sure you use the same F_SEP here
PROJ_TAG: "ProteinID"

F_SEP: "_" # underscore
#F_SEP: "-" # dash

# The name of the PBS queue
QUEUE: "my_cpu_alloc"

# The command used to submit to the queue
SUB_C: "qsub"

# The extension used for the current trajectory files
# Include this because we have a tendency to use mdcrd for nc files but
# you might change to the right ones in your later projects...
CUR_TRAJ_EXT: "mdcrd"

# The residue ranges for the standard cpptraj analysis. (ex: protein/nuc 1-455)
START_RES_RANGE: "1"
END_RES_RANGE: "392"

# The number of amino acids for the secondary structure analysis (ex: 1-430)
NUM_AA: "430"

# The divisor to use for the RMSD graphs to get the of frames per nanosecond.
# Typically, if you use Langevin this is 100, and 500 for Berendsen.
# This will be put in the gnuplot script as ($1/(TIME_DIVIDER)).
TIME_DIVIDER: "100"

# Residue of interest for EDA.
# The interaction of every residue with this residue, with the exception of
# those directly connected to it, will be calculated.
ROI: "250"

# TODO: Add SLURM script option
# TODO: Add LSF script option
